# Generated by Django 3.2.9 on 2021-11-23 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('fee', models.DecimalField(decimal_places=7, default=0, max_digits=7)),
                ('extra_fee', models.DecimalField(decimal_places=7, default=0, max_digits=7)),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park.carpark')),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park.parkingslot')),
            ],
        ),
    ]
