# Generated by Django 3.2.9 on 2021-12-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed')], default='Booked', max_length=10),
        ),
    ]
