# Generated by Django 3.2.9 on 2021-12-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='car',
        ),
    ]
