# Generated by Django 3.2.9 on 2021-12-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0002_parkingslot_slot_id'),
        ('user', '0003_delete_userrole'),
        ('car', '0002_car_guest'),
        ('parking', '0002_parking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AddField(
            model_name='parking',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='estimate_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='is_paid',
            field=models.BooleanField(default=False),
        )
    ]
