# Generated by Django 3.2.9 on 2021-12-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_security_car_park'),
        ('car_park', '0002_parkingslot_slot_id'),
        ('parking', '0002_parking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='estimate_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Booking', 'Booking'), ('Extra', 'Extra')], default='Booking', max_length=10)),
                ('fee', models.DecimalField(decimal_places=7, default=0, max_digits=7)),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park.carpark')),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park.parkingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guest')),
            ],
        ),
    ]
