# Generated by Django 3.2.9 on 2022-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20211231_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
