# Generated by Django 3.2.9 on 2021-12-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20211201_1642'),
        ('parking', '0003_auto_20211202_0934'),
    ]

    operations = [
    ]
