# Generated by Django 3.2.9 on 2022-01-07 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
