# Generated by Django 3.2.9 on 2021-12-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211203_1128'),
        ('parking', '0004_merge_0003_auto_20211201_1642_0003_auto_20211202_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='user.guest'),
        ),
    ]
