# Generated by Django 3.2.9 on 2021-12-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_parking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='done',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='extra_fee',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
