# Generated by Django 3.2.9 on 2021-12-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20211211_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='estimate_end_time',
        ),
    ]
