# Generated by Django 3.2.9 on 2021-12-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='slot_id',
        ),
    ]
