# Generated by Django 3.2.9 on 2021-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='slot_id',
            field=models.CharField(default='', max_length=5),
        ),
    ]
