# Generated by Django 4.0 on 2021-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('floor', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('data', models.IntegerField(default=0)),
            ],
        ),
    ]
