# Generated by Django 4.0 on 2021-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='floor',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
