# Generated by Django 3.2.9 on 2021-12-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('license_plate', models.CharField(default='', max_length=20, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('car_registration', models.ImageField(null=True, upload_to='car-registrations')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='user.guest')),
            ],
        ),
    ]
