# Generated by Django 3.2.9 on 2021-11-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('car_registration', models.CharField(max_length=20)),
            ],
        ),
    ]
