# Generated by Django 3.2.9 on 2021-11-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='car_park',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='car_park.carpark'),
        ),
    ]
