# Generated by Django 3.2.9 on 2022-01-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_guest_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='license',
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
