# Generated by Django 3.2.9 on 2021-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
