# Generated by Django 3.2.9 on 2021-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_guest_guest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='license_plate',
            field=models.ImageField(upload_to='media/license'),
        ),
    ]
