# Generated by Django 3.2.9 on 2021-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_guest_license_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest'},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='guest',
            name='license',
            field=models.ImageField(null=True, upload_to='licenses'),
        ),
    ]
